// spa/react-minimal/src/pages/Contact.js
import React from 'react';
import { Area } from '@magnolia/react-editor';

const Contact = props => {
  const { main, title } = props;
  const boxStyle = {
    background: '#eaf7f5',
    padding: '20px'
  };

  return (
    <div className="Contact">
      <h2  className="hint">[Contact Page]</h2>
      <div className="box" style={boxStyle}>
        <h1>{title || 'Nulla vitae elit libero, a pharetra augue.'}</h1>
      </div>
      {main && <Area content={main} />}
    </div>
  );
};

export default Contact;

// spa/angular-minimal/src/app/pages/contact/contact.component.ts
import { Component, Input } from '@angular/core';

@Component({
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss']
})
export class ContactComponent {
  @Input() content: any;
}

<div class="Contact">
  <div class="hint">[Contact Page]</div>
  <h1>{{content?.title}}</h1>
  
  <main>
    <div class="box" style="background:'#eaf7f5'">
      <h1>Kontaktiko! Nulla vitae elit libero, a pharetra augue.</h1>
    </div>

    <div mgnl-area [name]="'main'" [content]="content"></div>
  </main>
</div>
