// spa/angular-universal-minimal/src/app/pages/basic/basic.component.ts
import { Component, Input } from '@angular/core';

@Component({
  templateUrl: './basic.component.html',
  styleUrls: ['./basic.component.scss']
})
export class BasicComponent {
  @Input() title: any;

  @Input() main: any;
  @Input() extras: any;
  // metadata
  @Input() metadata: any;
}

<div class="Basic">
  <div class="hint">[Basic Page]</div>
  <h1>{{ title || metadata["@name"] }}</h1>

  <main>
    <div class="hint">[Main Area]</div>
    <div
      editable-area
      [content]="main"
      [parentTemplateId]="metadata['mgnl:template']"
    ></div>
  </main>

  <div class="Extras">
    <div class="hint">[Extras Area]</div>
    <div
      editable-area
      [content]="extras"
      [parentTemplateId]="metadata['mgnl:template']"
    ></div>
  </div>
</div>

// spa/vue-minimal/src/pages/Basic.vue
<template>
  <div class="Basic">
    <div className="hint">[Basic Page]</div>
    <h1>{{ title || metadata['@name'] }}</h1>
    
    <main>
      <div class="hint">[Main Area]</div>         
      <EditableArea v-if="main" v-bind:content="main" />
    </main>

    <div class="Extras">
      <div class="hint">[Extras Area]</div> 
      <EditableArea v-if="extras" v-bind:content="extras" />
    </div>
  </div>
</template>

<script>
import { EditableArea } from '../vue-editor';

export default {
  name: 'Basic',
  components: {
    EditableArea,
  },
  props: ['title', 'metadata', 'main', 'extras'],
};
</script>
