// spa/react-minimal/src/pages/Basic.js
import React from 'react';
import { EditableArea } from '@magnolia/react-editor';

const Basic = props => {
  const { main, extras, title } = props;

  return (
    <div className="Basic">
      <div className="hint">[Basic Page]</div>
      <h1>{title || props.metadata['@name']}</h1>

      <main>
        <div className="hint">[Main Area]</div>         
        {main && <EditableArea className="Area" content={main} />}  
      </main>

      <div className="Extras" >
        <div className="hint">[Sercondary Area]</div>
        {extras && <EditableArea className="Area" content={extras} />}  
        {/* <button>Contact</button> */}
      </div>    
    </div>
  ) 
};

export default Basic;

// spa/vue-minimal/src/pages/Basic.vue
<template>
  <div class="Basic">
    <div class="hint">[Basic Page]</div>
    <h1>{{ title || metadata['@name'] }}</h1>

    <main>
      <div class="hint">[Main Area]</div>
      <EditableArea v-if="main" v-bind:content="main" />
    </main>

    <div class="Extras">
      <div class="hint">[Extras Area]</div>
      <EditableArea v-if="extras" v-bind:content="extras" />
    </div>
  </div>
</template>

<script>
import { EditableArea } from '@magnolia/vue-editor';

export default {
  name: 'Basic',
  components: {
    EditableArea
  },
  props: ['title', 'metadata', 'main', 'extras']
};
</script>
