// spa/angular-universal-minimal/src/app/components/expander/expander.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-expander',
  templateUrl: './expander.component.html',
  styleUrls: ['./expander.component.scss']
})
export class ExpanderComponent  {

  @Input() expanderItems: any;

  // metadata
  @Input() metadata: any;

  isExpanded = false;

  toggleArea() {
    this.isExpanded = !this.isExpanded;
  }

}

<div class="expander">
    <div (click)="toggleArea()" 
    [ngClass]="isExpanded ? 'open expanderHeader' : 'closed expanderHeader'"
    >
      Expander
      <svg class="expanderIcon" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"></path></svg>
    </div>
    
    
      <div *ngIf="isExpanded">
        <div class="hint">[EXPANDER OPENED]</div>
        <ul editable-area [content]="expanderItems"  [parentTemplateId]="metadata['mgnl:template']"></ul>

      </div>
    
  </div>

// spa/nuxtjs-v3-ssr-minimal/templates/components/Expander.vue
<template>
  <div class="Expander">
    <div
      @click.prevent="toggle"
      class="expanderHeader"
      :class="isCollapsed ? 'closed' : 'open'"
    >
      Expander
      <svg
        class="expanderIcon"
        focusable="false"
        viewBox="0 0 24 24"
        aria-hidden="true"
        role="presentation"
      >
        <path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z" />
      </svg>
    </div>

    <div v-if="!isCollapsed">
      <div class="hint">[EXPANDER OPENED]</div>
      <EditableArea
        v-if="expanderItems"
        v-bind:content="expanderItems"
        v-bind:parentTemplateId="metadata['mgnl:template']"
      />
    </div>
  </div>
</template>

<script>
import { EditableArea } from "@magnolia/vue-editor";

export default {
  name: "Expander",
  components: {
    EditableArea,
  },
  props: ["expanderItems", "metadata"],

  data() {
    return {
      isCollapsed: true,
    };
  },

  methods: {
    toggle() {
      this.isCollapsed = !this.isCollapsed;
    },
  },
};
</script>
