// spa/react-minimal/src/helpers/PageLoader.js
import React from 'react';
import config from '../magnolia.config';
import { getAPIBase, getLanguages, removeCurrentLanguage, getCurrentLanguage, getVersion } from './AppHelpers';

import { EditablePage, EditorContextHelper } from '@magnolia/react-editor';

class PageLoader extends React.Component {
  state = {};

  getPagePath = () => {
    const languages = getLanguages();
    const nodeName = process.env.REACT_APP_MGNL_APP_BASE;
    const currentLanguage = getCurrentLanguage();
    let path = nodeName + this.props.pathname.replace(new RegExp('(.*' + nodeName + '|.html)', 'g'), '');

    if (currentLanguage !== languages[0]) {
      path = removeCurrentLanguage(path, currentLanguage);
      path += '?lang=' + currentLanguage;
    }

    return path;
  };

  loadPage = async () => {
    // Bail out if already loaded content.
    if (this.state.pathname === this.props.pathname) return;

    const apiBase = getAPIBase();

    const pagePath = this.getPagePath();
    console.log('pagePath:' + pagePath);
    const config = {
      headers: {},
    };

    const isPersonalizationPage = sessionStorage.getItem(`personalized_${this.props.pathname.replace(/\//g, '_')}`);

    const params = new URLSearchParams(window.location.search);

    const version = getVersion(window.location.href);

    if (version) {
      params.append('version', version);
    }

    if (params.get('mgnlPreviewAsVisitor') !== 'true' && EditorContextHelper.inIframe()) {
      params.append('variants', 'all');
    }

    const queryString = params.toString();

    const ageHeader = sessionStorage.getItem('mgnlAgeHeader');
    if (isPersonalizationPage && ageHeader && !EditorContextHelper.inIframe()) {
      config.headers['X-Mgnl-Age'] = ageHeader;
    }

    let fullContentPath = `${apiBase}${
      version ? process.env.REACT_APP_MGNL_API_PAGES_PREVIEW : process.env.REACT_APP_MGNL_API_PAGES
    }${pagePath}`;

    if (queryString) {
      if (fullContentPath.includes('?')) {
        fullContentPath += '&';
      } else {
        fullContentPath += '?';
      }

      fullContentPath += queryString;
    }

    const pageResponse = await fetch(fullContentPath, config);
    const pageJson = await pageResponse.json();
    console.log('page content: ', pageJson);

    const templateId = pageJson['mgnl:template'];
    console.log('templateId:', templateId);

    let templateJson = {};

    if (window.location.search.includes('mgnlPreview')) {
      const templateResponse = await fetch(apiBase + process.env.REACT_APP_MGNL_API_TEMPLATES + pagePath);
      templateJson = await templateResponse.json();
      console.log('definition:', templateJson);
    }

    this.setState({
      init: true,
      content: pageJson,
      templateAnnotations: templateJson,
      pathname: this.props.pathname,
    });
  };

  componentDidMount() {
    this.loadPage();
  }

  componentDidUpdate() {
    this.loadPage();
  }

  render() {
    console.log('this.props.pathname', this.props.pathname);

    if (this.state.init) {
      console.log('config:', config);
      //const isDevMode = process.env.NODE_ENV === 'development';
      //console.log("n:" + process.env.NODE_ENV)

      return (
        <EditablePage
          templateAnnotations={this.state.templateAnnotations || {}}
          content={this.state.content}
          config={config}
        ></EditablePage>
      );
    } else {
      return <p>NO PAGE.</p>;
    }
  }
}

export default PageLoader;

// spa/vue-minimal/src/helpers/PageLoader.vue
<template>
  <EditablePage
    v-if="content && templateAnnotations"
    v-bind:content="content"
    v-bind:config="config"
    v-bind:templateAnnotations="templateAnnotations"
  />
</template>

<script>
import { EditablePage, EditorContextHelper } from '@magnolia/vue-editor';
import { getLanguages, getCurrentLanguage, removeCurrentLanguage, removeExtension, getVersion } from './AppHelpers';
import config from '../magnolia.config';

const getPath = () => {
  const nodeName = process.env.VUE_APP_MGNL_SITE_PATH;
  let path = nodeName + window.location.pathname.replace(new RegExp('(.*' + nodeName + '|.html)', 'g'), '');

  return path;
};

const getServerPathUrl = () => {
  return process.env.VUE_APP_MGNL_HOST + process.env.VUE_APP_MGNL_BASE_AUTHOR;
};

const getContentUrl = () => {
  const languages = getLanguages();
  const nodeName = process.env.VUE_APP_MGNL_SITE_PATH;
  const currentLanguage = getCurrentLanguage();
  let path = nodeName + window.location.pathname.replace(new RegExp('(.*' + nodeName + '|.html)', 'g'), '');

  if (currentLanguage !== languages[0]) {
    path = removeCurrentLanguage(path, currentLanguage);
    path += '?lang=' + currentLanguage;
  }

  const version = getVersion(window.location.href);
  if (version) {
    path += path.indexOf('?') > -1 ? '&version=' + version : '?version=' + version;
  }

  return `${process.env.VUE_APP_MGNL_API_PAGES}${path}`;
};

export default {
  name: 'PageLoader',
  components: {
    EditablePage,
  },
  data() {
    return {
      content: null,
      templateAnnotations: {},
      config,
    };
  },
  methods: {
    async loadPageContent() {
      const contentUrl = getContentUrl();

      console.log('Get Content: ' + contentUrl);

      const contentResponse = await fetch(contentUrl);
      const content = await contentResponse.json();
      const templateId = content['mgnl:template'];
      if (!templateId) {
        return;
      }

      // Get Template Annotations

      const path = getPath();
      const templateEndpointUrl = getServerPathUrl() + process.env.VUE_APP_MGNL_API_TEMPLATES + removeExtension(path);

      console.log('Get Template Info: ' + templateEndpointUrl);

      if (window.location.search.includes('mgnlPreview')) {
        const templateResponse = await fetch(templateEndpointUrl);
        const templateAnnotations = await templateResponse.json();

        this.templateAnnotations = templateAnnotations;
      }

      this.content = content;
    },
  },
  mounted() {
    this.loadPageContent();
  },
};
</script>

<style></style>
