// spa/react-minimal/src/components/List.js
import React from 'react';
import { Area } from '@magnolia/react-editor';

const List = props => {

  const { items} = props;

  return (
    <>
    <div className="hint">[LIST]</div>
    <ul className="List">
      {items && <Area content={items} parentTemplateId={props.metadata['mgnl:template']}/>}
    </ul>
    </>

  );
};

export default List;

// spa/vue-minimal/src/components/List.vue
<template>
  <ul class="List">
    <EditableArea
      v-if="items"
      v-bind:content="items"
      v-bind:parentTemplateId="metadata['mgnl:template']"
    />
  </ul>
</template>

<script setup>
import { defineProps } from 'vue';
import { EditableArea } from '@magnolia/vue-editor';

defineProps({
  items: Object,
  metadata: Object
});
</script>
