// spa/react-minimal/src/components/Navigation.js
import React from 'react';
import { NavLink } from 'react-router-dom';
import { getAPIBase, getLanguages, getCurrentLanguage, changeLanguage } from '../helpers/AppHelpers';

function renderLanguages() {
  const currentLanguage = getCurrentLanguage();

  return (
    <div className='languages'>
      {getLanguages().map((lang) => (
        <span key={`lang-${lang}`} data-active={currentLanguage === lang} onClick={() => changeLanguage(lang)}>
          {lang}
        </span>
      ))}
    </div>
  );
}

function Navigation() {
  const [navItems, setNavItems] = React.useState([]);

  React.useEffect(() => {
    async function fetchNav() {
      const apiBase = getAPIBase();
      const url = apiBase + process.env.REACT_APP_MGNL_API_NAV + process.env.REACT_APP_MGNL_APP_BASE;
      console.log('NAV URL:' + url);
      const response = await fetch(url);
      const data = await response.json();
      let items = data['@nodes'].map((nodeName) => {
        return data[nodeName];
      });
      setNavItems([data, ...items]);
    }

    if (navItems.length < 1) {
      fetchNav();
    }
  }, [navItems]);

  return navItems ? (
    <nav className='Navigation'>
      {navItems.map((item) => {
        return (
          <NavLink key={item['@id']} to={item['@path'].replace(process.env.REACT_APP_MGNL_APP_BASE, '')}>
            {item.navigationTitle || item.title || item['@name']}
          </NavLink>
        );
      })}
      {renderLanguages()}
    </nav>
  ) : (
    <div />
  );
}

export default Navigation;

// spa/vue-minimal/src/components/Navigation.vue
<template>
  <nav v-if="pagenav">
    <router-link
      v-for="item in pagenav"
      :key="item['@id']"
      v-bind:to="item['@name']"
    >{{ item.title }}</router-link>
    <div class="languages">
      <span
        v-for="language in languages"
        :key="language"
        :data-active="currentLanguage === language"
        @click="(e)=>$router.push(clickLanguage(language))"
      >{{ language }}</span>
    </div>
  </nav>
</template>

<script>
import {
  getLanguages,
  getCurrentLanguage,
  changeLanguage
} from '../helpers/AppHelpers';

export default {
  name: 'Navigation',
  data() {
    return {
      pagenav: [],
      languages: getLanguages(),
      currentLanguage: getCurrentLanguage()
    };
  },

  async mounted() {

    let url = process.env.VUE_APP_MGNL_API_NAV + process.env.VUE_APP_MGNL_SITE_PATH;

    console.log('Get Nav Con  : ' + url)

    const pagenavResponse = await fetch(url);
    const pagenav = await pagenavResponse.json();
    const newPagenav = [
      {
        '@id': pagenav['@id'],
        '@name': '/',
        title: pagenav.title
      }
    ];

    this.pagenav = newPagenav.concat(
      pagenav['@nodes'].map(nodeName => pagenav[nodeName])
    );
  },

  methods: {
    clickLanguage: function(language) {
      return changeLanguage(language);
    }
  }
};
</script>
