// spa/vue-minimal/src/components/Expander.vue
<template>
  <div class="Expander">
    <div @click.prevent="toggle" class="expanderHeader" :class="isCollapsed ? 'closed' : 'open'">
      Expander
      <svg
        class="expanderIcon"
        focusable="false"
        viewBox="0 0 24 24"
        aria-hidden="true"
        role="presentation"
      >
        <path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z" />
      </svg>
    </div>

    <div v-if="!isCollapsed">
      <div class="hint">[EXPANDER OPENED]</div>
      <EditableArea
        v-if="expanderItems"
        v-bind:content="expanderItems"
        v-bind:parentTemplateId="metadata['mgnl:template']"
      />
    </div>
  </div>
</template>

<script>
import { EditableArea, inEditorEdit } from '@magnolia/vue-editor';

export default {
  name: 'Expander',
  components: {
    EditableArea
  },
  props: ['expanderItems', 'metadata'],

  data() {
    return {
      isCollapsed: true
    };
  },

  updated() {
    if (inEditorEdit && window.parent.mgnlRefresh) {
      window.parent.mgnlRefresh();
    }
  },

  methods: {
    toggle() {
      this.isCollapsed = !this.isCollapsed;
    }
  }
};
</script>

// spa/react-minimal/src/components/Expander.js
import React from 'react';
import { EditableArea, EditorContextHelper } from '@magnolia/react-editor';

class Expander extends React.Component {

  constructor(props) {
    super(props);
    this.state = {isCollapsed: true};
    this.toggle = this.toggle.bind(this);
  }

  state = {};
 
  toggle(event) {
    this.setState({
      isCollapsed: !this.state.isCollapsed
    });
    event.preventDefault();
  }

  componentDidUpdate() {
    EditorContextHelper.refresh();
    // if (window.parent.mgnlRefresh !== undefined){
    //   EditorContextHelper.refresh();
    // }
  }

  render () {
    const expanderItems = this.props.expanderItems;
    return (
      <div className="expander">
        <div onClick={this.toggle} className={this.state.isCollapsed ? 'open expanderHeader' : 'closed expanderHeader'}>
          Expander
          <svg className="expanderIcon" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"></path></svg>
        </div>
        
        {!this.state.isCollapsed &&
          <div>
            <div className="hint">[EXPANDER OPENED]</div>
            {expanderItems && <EditableArea content={expanderItems}  parentTemplateId={this.props.metadata['mgnl:template']}/>}
          </div>
        }   
      </div>
    );
  }
  

};

export default Expander;
