// spa/angular-minimal/src/app/components/list/list.component.ts
import { Component, Input } from '@angular/core';

@Component({
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.scss']
})
export class ListComponent {
  @Input() content: any;
}

<div class="hint">[LIST]</div>

<ul editable-area class="List" [content]="items"  [parentTemplateId]="metadata['mgnl:template']"></ul>

// spa/react-minimal/src/components/List.js
import React from 'react';
import { Area } from '@magnolia/react-editor';

const List = props => {

  const { items} = props;

  return (
    <>
    <div className="hint">[LIST]</div>
    <ul className="List">
      {items && <Area content={items} parentTemplateId={props.metadata['mgnl:template']}/>}
    </ul>
    </>

  );
};

export default List;
