// spa/angular-minimal/src/app/components/navigation/navigation.component.ts
import { Component, Input, AfterContentInit } from '@angular/core';
import { getLanguages, getCurrentLanguage, changeLanguage } from 'src/app/helpers/AppHelpers';
import { environment } from 'src/environments/environment';
import { Router } from '@angular/router';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
})
export class NavigationComponent implements AfterContentInit {
  navItems: object;
  languages: Array<string>;
  currentLanguage: string;

  @Input() content: object;
  constructor(private router: Router) {
    this.languages = getLanguages();
    this.currentLanguage = getCurrentLanguage();
  }

  async fetchNav(): Promise<Array<Object>> {
    const url = environment.navUrl + environment.appBase;
    console.log('NAV URL:' + url);
    const response = await fetch(url);
    const data = await response.json();
    return data;
  }

  ngAfterContentInit(): void {
    if (!this.navItems) {
      this.fetchNav().then((data) => {
        let items = data['@nodes'].map((nodeName) => {
          return data[nodeName];
        });
        this.navItems = [data, ...items];
      });
    }
  }

  getLink(item: object): string {
    return item['@path'].replace(environment.appBase, '');
  }

  isActive(item: object): boolean {
    const path = this.getRelativePath(item['@path']);
    let { url } = this.router;
    url = url.replace(/\.html.*$/, '');
    url = url === '' ? '/' : url;
    return url === path;
  }

  getRelativePath(path: string): string {
    const relativePath = path.substring(environment.appBase.length);
    return relativePath === '' ? '/' : relativePath;
  }

  clickLanguage(language: string): void {
    changeLanguage(language);
  }
}

<nav class="Navigation">
  <ng-template ngFor let-item [ngForOf]="navItems">
    <a [ngClass]="{ active: isActive(item) }" [routerLink]="getLink(item)">{{
      item.navigationTitle || item.title || item['@name']
    }}</a>
  </ng-template>
  <div class="languages">
    <span
      *ngFor="let language of languages"
      [ngClass]="{ active: currentLanguage === language }"
      (click)="clickLanguage(language)"
      >{{ language }}</span
    >
  </div>
</nav>

// spa/react-minimal/src/components/Navigation.js
import React from 'react';
import { NavLink } from 'react-router-dom';
import { getAPIBase, getLanguages, getCurrentLanguage, changeLanguage } from '../helpers/AppHelpers';

function renderLanguages() {
  const currentLanguage = getCurrentLanguage();

  return (
    <div className='languages'>
      {getLanguages().map((lang) => (
        <span key={`lang-${lang}`} data-active={currentLanguage === lang} onClick={() => changeLanguage(lang)}>
          {lang}
        </span>
      ))}
    </div>
  );
}

function Navigation() {
  const [navItems, setNavItems] = React.useState([]);

  React.useEffect(() => {
    async function fetchNav() {
      const apiBase = getAPIBase();
      const url = apiBase + process.env.REACT_APP_MGNL_API_NAV + process.env.REACT_APP_MGNL_APP_BASE;
      console.log('NAV URL:' + url);
      const response = await fetch(url);
      const data = await response.json();
      let items = data['@nodes'].map((nodeName) => {
        return data[nodeName];
      });
      setNavItems([data, ...items]);
    }

    if (navItems.length < 1) {
      fetchNav();
    }
  }, [navItems]);

  return navItems ? (
    <nav className='Navigation'>
      {navItems.map((item) => {
        return (
          <NavLink key={item['@id']} to={item['@path'].replace(process.env.REACT_APP_MGNL_APP_BASE, '')}>
            {item.navigationTitle || item.title || item['@name']}
          </NavLink>
        );
      })}
      {renderLanguages()}
    </nav>
  ) : (
    <div />
  );
}

export default Navigation;
