// spa/angular-minimal/src/app/navigation/navigation.component.ts
import { Component, Input, AfterContentInit } from '@angular/core';
import { environment } from 'src/environments/environment';
import { Router } from '@angular/router';

@Component({
    selector: 'app-navigation',
    templateUrl: './navigation.component.html'
})
export class NavigationComponent implements AfterContentInit {
    navItems: object;
    @Input() content: object;
    constructor(private router: Router) {}

    async fetchNav(): Promise<Array<Object>> {
        const url = environment.navUrl + environment.appBase;
        console.log('NAV URL:' + url);
        const response = await fetch(url);
        const data = await response.json();
        return data;
    }

    ngAfterContentInit(): void {
        
        if (!this.navItems) {
            this.fetchNav().then(data => {
                let items = data['@nodes'].map(nodeName => {return data[nodeName]})
                this.navItems = [data, ...items];
            });
        }
    }

    getLink(item: object): string {
        const path = this.getRelativePath(item['@path']);
        return `${path.endsWith('/') ? path : `${path.substr(0, path.length)}.html`}`;
    }

    isActive(item: object): boolean {
        const path = this.getRelativePath(item['@path']);
        let { url } = this.router;
        url = url.replace(/\.html.*$/, '');
        url = url === '' ? '/' : url;
        return url === path;
    }

    getRelativePath(path: string): string {
        const relativePath = path.substring(environment.appBase.length);
        return relativePath === '' ? '/' : relativePath;
    }

}

// spa/react-minimal/src/components/Navigation.js
import React from 'react';
import { NavLink } from 'react-router-dom';

//TODO - Is this still needed now that we use .env files?
function removeAppBase(path){
    const base = process.env.REACT_APP_MGNL_APP_BASE
    if (base !== ''){
        if (base === path.substring(0, base.length)){
            return path.substring(base.length);
        }
    }
    return path;
}


function Navigation() {
    const [navItems, setNavItems] = React.useState([]);

    React.useEffect(() => {

        async function fetchNav() {
            const url = process.env.REACT_APP_MGNL_API_NAV + process.env.REACT_APP_MGNL_APP_BASE;
            console.log('NAV URL:' + url);
            const response = await fetch(url);
            const data = await response.json();
            let items = data['@nodes'].map(nodeName => {return data[nodeName]})
            setNavItems([data, ...items]);
        }

        if (navItems.length < 1) {
            fetchNav();
        }
    },[navItems]);

    
    return (navItems) ? (
        
        <nav className="Navigation">
            {
                navItems.map(item => {
                    return <NavLink activeClassName="active" key={item['@id']} to={`${removeAppBase(item['@path'])}.html`}>{item.navigationTitle || item.title || item['@name']}</NavLink>
                })
            }
        </nav>

    ) : (<div />);
}

export default Navigation;
