// spa/vue-minimal/src/components/PageWrapper.vue
<template>
  <Page v-if="page" v-bind:page="page" />
</template>

<script>
import Page from "vue-magnolia/Page";

const isInAuthor = window.self !== window.top && window.singlePageConfig;

export default {
  name: "PageWrapper",
  components: {
    Page
  },
  data: function() {
    return {
      page: isInAuthor ? window.singlePageConfig.content : undefined
    };
  },
  methods: {
    getPage() {
      if (isInAuthor) return;

      const path = window.location.pathname.replace("/magnoliaAuthor", "");

      fetch("http://localhost:8080/magnoliaAuthor/.rest/pages" + path)
        .then(res => res.json())
        .then(json => (this.page = json));
    }
  },
  mounted() {
    this.getPage();
  }
};
</script>

// spa/react-minimal/src/components/PageWrapper.js
import React from 'react';
import { Page } from 'react-magnolia';

const isInAuthor = window.self !== window.top && window.singlePageConfig;

class PageWrapper extends React.Component {
  state = {
    page: isInAuthor ? window.singlePageConfig.content : {}
  };

  getPage = () => {
    if (isInAuthor || this.state.pathname === window.location.pathname) return;

    const path = window.location.pathname.replace('/magnoliaAuthor', '');

    fetch('http://localhost:8080/magnoliaAuthor/.rest/pages' + path)
      .then(res => res.json())
      .then(json => this.setState({ page: json, pathname: window.location.pathname }));
  };

  componentDidMount() {
    this.getPage();
  }

  componentDidUpdate() {
    this.getPage();
  }

  render() {
    const { page } = this.state;

    return page ? <Page {...page} /> : null;
  }
}

export default PageWrapper;
