// spa/angular-minimal/src/app/pages/basic/basic.component.ts
import { Component, Input } from '@angular/core';

@Component({
  templateUrl: './basic.component.html',
  styleUrls: ['./basic.component.scss']
})
export class BasicComponent {
  @Input() content: any;
}

<div class="Basic">
    <div class="hint">[Basic Page]</div>    
    <h1>{{title || metadata['@name']}}</h1>
    
    <main>
        <div class="hint">[Main Area]</div>         
        <div editable-area  [content]="main" [parentTemplateId]="metadata['mgnl:template']"></div>  
    </main>
    
    <div class="Extras" >
        <div class="hint">[Extras Area]</div>
        <div editable-area  [content]="extras" [parentTemplateId]="metadata['mgnl:template']"></div>
        <button routerLink="/contact">Contact</button>
    </div>

</div>

// spa/react-minimal/src/pages/Basic.js
import React from 'react';
import { Area } from '@magnolia/react-editor';

const Basic = props => {
  const { main, extras, title } = props;

  return (
    <div className="Basic">
      <div className="hint">[Basic Page]</div>
      <h1>{title || props.metadata['@name']}</h1>

      <main>
        <div className="hint">[Main Area]</div>         
        {main && <Area className="Area" content={main} />}  
      </main>

      <div className="Extras" >
        <div className="hint">[Sercondary Area]</div>
        {extras && <Area className="Area" content={extras} />}  
        {/* <button>Contact</button> */}
      </div>    
    </div>
  ) 
};

export default Basic;
