// spa/nuxtjs-ssr-minimal/templates/pages/Contact.vue
<template>
  <div class="Contact">
    <h2 class="hint">[Contact Page]</h2>
    <div class="box">
      <h1>{{ title || "Nulla vitae elit libero, a pharetra augue." }}</h1>
    </div>
    <EditableArea v-if="main" v-bind:content="main" />
  </div>
</template>

<script>
import { EditableArea } from "@magnolia-services/vue2-editor";

export default {
  name: "Contact",
  components: {
    EditableArea,
  },
  props: ["title", "metadata", "main"],
};
</script>

<style scoped>
.box {
  background: #eaf7f5;
  padding: 20px;
}
</style>

// spa/react-minimal/src/pages/Contact.js
import React from 'react';
import { Area } from '@magnolia/react-editor';

const Contact = props => {
  const { main, title } = props;
  const boxStyle = {
    background: '#eaf7f5',
    padding: '20px'
  };

  return (
    <div className="Contact">
      <h2  className="hint">[Contact Page]</h2>
      <div className="box" style={boxStyle}>
        <h1>{title || 'Nulla vitae elit libero, a pharetra augue.'}</h1>
      </div>
      {main && <Area content={main} />}
    </div>
  );
};

export default Contact;
