// spa/vue-minimal/src/pages/Contact.vue
<template>
  <div class="Contact">
    <div class="box">
      <h1>Nulla vitae elit libero, a pharetra augue.</h1>
    </div>
    <Area v-if="main" v-bind:area="main" />
  </div>
</template>

<script>
import Area from "vue-magnolia/Area";

export default {
  name: "Contact",
  components: {
    Area
  },
  props: ["main"]
};
</script>

<style scoped>
.box {
  background: #eaf7f5;
  padding: 20px;
}
</style>

// spa/react-minimal/src/pages/Contact.js
import React from 'react';
import { Area } from 'react-magnolia';

const Contact = props => {
  const { main } = props;
  const boxStyle = {
    background: '#eaf7f5',
    padding: '20px'
  };

  return (
    <div className="Contact">
      <div className="box" style={boxStyle}>
        <h1>Nulla vitae elit libero, a pharetra augue.</h1>
      </div>
      {main && <Area {...main} />}
    </div>
  );
};

export default Contact;
